
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-dining
owner: ucsb-cs156
repo_name: proj-dining
pull_requests: [{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/refactor-github-workflows","number":104,"title":"Refactor proj-dining GitHub Actions to use centralized reusable workflows (including Dokku deploy flow)","url":"https://github.com/ucsb-cs156/proj-dining/pull/104"},{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/separate-jpa-auditing-handler","number":103,"title":"Extract JPA auditing config and remove unnecessary test DB bootstrapping","url":"https://github.com/ucsb-cs156/proj-dining/pull/103"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-no-swagger-on-prod","number":101,"title":"pc - update prod value of show swagger to false","url":"https://github.com/ucsb-cs156/proj-dining/pull/101"}]
