
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-dining
owner: ucsb-cs156
repo_name: proj-dining
pull_requests: [{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/allow-feedback-button-when-app-feedback-url-enable","number":146,"title":"[WIP] Add feedback button to footer when APP_FEEDBACK_URL is set","url":"https://github.com/ucsb-cs156/proj-dining/pull/146"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-speedUpMenuItemProcessing","number":143,"title":"Speeding Up the Dining Commons Menu Item Page","url":"https://github.com/ucsb-cs156/proj-dining/pull/143"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-advancedConfig","number":142,"title":"Apply a Rate Limiting Scheme to Non-University IP Addresses","url":"https://github.com/ucsb-cs156/proj-dining/pull/142"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-addNginxConfig","number":141,"title":"Apply Nginx-Level Rate Limiting","url":"https://github.com/ucsb-cs156/proj-dining/pull/141"}]
